# These are supported funding model platforms

github: # [@labibkhanofficialbd, @Code-Hunter-OfficialBD]
patreon: # @labibkhanofficialbd
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
otechie: # @Code-Hunter-OfficialBD
custom: ['http://codehunter.rf.gd', 'http://irtizakhanlabib.rf.gd']
